# Generated by Django 5.0.3 on 2026-03-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('org_type', models.CharField(choices=[('TOO', 'ТОО (Товарищество с ограниченной ответственностью)'), ('AO', 'АО (Акционерное общество)'), ('NAO', 'НАО (Непубличное акционерное общество)'), ('IP', 'ИП (Индивидуальный предприниматель)'), ('GP', 'ГП (Государственное предприятие)'), ('OTHER', 'Иное')], max_length=10, verbose_name='Тип организации')),
                ('region', models.CharField(choices=[('akmola', 'Акмолинская область'), ('aktobe', 'Актюбинская область'), ('almaty_reg', 'Алматинская область'), ('atyrau', 'Атырауская область'), ('east_kaz', 'Восточно-Казахстанская область'), ('zhambyl', 'Жамбылская область'), ('zhetysu', 'Жетысуская область'), ('west_kaz', 'Западно-Казахстанская область'), ('karaganda', 'Карагандинская область'), ('kostanay', 'Костанайская область'), ('kyzylorda', 'Кызылординская область'), ('mangistau', 'Мангистауская область'), ('pavlodar', 'Павлодарская область'), ('north_kaz', 'Северо-Казахстанская область'), ('turkestan', 'Туркестанская область'), ('ulytau', 'Улытауская область'), ('almaty_city', 'г. Алматы'), ('astana', 'г. Астана'), ('shymkent', 'г. Шымкент')], max_length=50, verbose_name='Область / регион')),
                ('industry', models.CharField(choices=[('education', 'Образование'), ('construction', 'Строительная'), ('chemical', 'Химическая'), ('food', 'Пищевая'), ('metallurgy', 'Металлургия'), ('light_industry', 'Лёгкая промышленность'), ('it_ai', 'ИИ / IT'), ('energy', 'Энергетика'), ('agriculture', 'Сельское хозяйство'), ('transport', 'Транспорт и логистика'), ('finance', 'Финансы и банки'), ('other', 'Иное')], max_length=50, verbose_name='Отрасль')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
    ]
