# Generated by Django 5.0.3 on 2026-03-09 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название опросника')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название периода')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('quarter', models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартал (1–4)')),
                ('start_date', models.DateField(verbose_name='Начало периода')),
                ('end_date', models.DateField(verbose_name='Конец периода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отчётный период',
                'verbose_name_plural': 'Отчётные периоды',
                'ordering': ['-year', '-quarter'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('E', 'Environmental (Экология)'), ('S', 'Social (Социальная)'), ('G', 'Governance (Управление)')], max_length=1, verbose_name='ESG категория')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('text', 'Текстовый ответ'), ('number', 'Числовой ответ'), ('choice', 'Один из вариантов'), ('multi_choice', 'Несколько вариантов'), ('scale', 'Шкала (1–5)'), ('boolean', 'Да / Нет')], default='text', max_length=20, verbose_name='Тип вопроса')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Варианты ответов (для choice/multi_choice)')),
                ('max_score', models.FloatField(default=10.0, verbose_name='Максимальный балл')),
                ('weight', models.FloatField(default=1.0, verbose_name='Весовой коэффициент')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reports.questionnaire', verbose_name='Опросник')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['questionnaire', 'category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлен'), ('reviewed', 'Проверен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('score_e', models.FloatField(blank=True, null=True, verbose_name='Балл E (экология)')),
                ('score_s', models.FloatField(blank=True, null=True, verbose_name='Балл S (социальный)')),
                ('score_g', models.FloatField(blank=True, null=True, verbose_name='Балл G (управление)')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='Итоговый балл')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company', verbose_name='Компания')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.questionnaire', verbose_name='Опросник')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Респондент')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reportingperiod', verbose_name='Отчётный период')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'questionnaire', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('E', 'Environmental (Экология)'), ('S', 'Social (Социальная)'), ('G', 'Governance (Управление)')], max_length=1, verbose_name='Категория')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание рекомендации')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Приоритет (1=высокий)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='reports.report', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'ordering': ['report', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('number_value', models.FloatField(blank=True, null=True, verbose_name='Числовой ответ')),
                ('choice_value', models.JSONField(blank=True, default=list, verbose_name='Выбранные варианты')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Балл за ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.question', verbose_name='Вопрос')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reports.report', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'unique_together': {('report', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.FloatField(verbose_name='Сырой балл')),
                ('weighted_score', models.FloatField(verbose_name='Взвешенный балл')),
                ('max_possible', models.FloatField(verbose_name='Максимально возможный балл')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.question', verbose_name='Вопрос')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='reports.report', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Балл',
                'verbose_name_plural': 'Баллы',
                'unique_together': {('report', 'question')},
            },
        ),
    ]
