# Generated by Django 5.0.14 on 2026-03-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_questionnaire_weights_question_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='score_formula',
            field=models.CharField(blank=True, choices=[('linear_desc', 'Убывающий (лучший = первый вариант)'), ('linear_asc', 'Возрастающий (лучший = последний вариант)'), ('binary', 'Бинарный (ответ есть → макс. балл)'), ('proportional', 'Пропорциональный (доля выбранных)'), ('scale_linear', 'Шкала линейная (value / max_scale)'), ('numeric_cap', 'Числовой с потолком (min(value, max_score))'), ('manual', 'Ручной ввод балла')], default='', help_text='Оставьте пустым — будет выбрано автоматически по типу вопроса', max_length=20, verbose_name='Правило расчёта балла'),
        ),
    ]
