# Generated by Django 5.0.14 on 2026-03-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
    ]
